spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.59.177:8848
    gateway:
      #      服务发现 http://127.0.0.1:1000/cloud-order/order/insert
      discovery:
        locator:
          enabled: true
      #      #      nacos 手动服务发现整合
      routes:
        #        http://127.0.0.1:1000/order-rpc/order/insert
        - id: order_route
          uri: lb://cloud-order
          predicates:
            - Path=/order-rpc/**
          filters:
            - StripPrefix=1
        #        #        #      手动配置路由
        #        #        # 访问http://127.0.0.1:1000/order-serv/order/insert
        #        - id: order_route1
        #          uri: http://localhost:1002
        #          predicates:
        #            - Path=/order-serv/**
        #          filters:
        #            - StripPrefix=1
        #         时间之前
        #        - id: after_route
        #          uri: https://www.baidu.com/
        #          predicates:
        #            - After=2000-01-20T17:42:47.789-07:00[America/Denver]
#        - id: cookie_route
#          uri: https://www.baidu.com/
#          predicates:
#            - Cookie=chocolate,ch.p
#        - id: header_route
#          uri: https://www.baidu.com/
#          predicates:
#            - Header=x-request-id,\d+
#        - id: method_route
#          uri: https://www.baidu.com/
#          predicates:
#           - Method=GET
#        - id: path_route
#          uri: https://www.baidu.com/
#          predicates:
#           - Path=/baidu/**
#        - id: query_route
#          uri: https://www.baidu.com/
#          predicates:
#           - Query=green,2

        - id: prefixPath_route
          uri: lb://cloud-order
          predicates:
            - Path=/order/**
#          添加请求头
          filters:
#            - PrefixPath=/order
            - AddRequestHeader=X-Request-red,blue
            - AddRequestParameter=color,blue
            - AddResponseHeader=X-Response-Red, Blue


